export const SET_BLOG_DATA = 'SET_BLOG_DATA';
export const SET_BLOG_LOADING = 'SET_BLOG_LOADING';
export const SET_FEATURED_BLOGS = 'SET_FEATURED_BLOGS';
export const SET_SEARCH_BLOGS = 'SET_SEARCH_BLOGS';
export const SET_CAREER_DATA = 'SET_CAREER_DATA';
export const SET_CAREER_LOADING = 'SET_CAREER_LOADING';
